// Records when the site was last built, so the footer can show a quiet
// "last updated" timestamp. Writes assets/js/build.js with the build time
// preformatted as YYYY.MM.DD HH:MM (build machine local time); main.js just
// pairs it with a localized label.
//
// Run: node tools/build-stamp.mjs   (invoked by build.sh)

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "assets", "js", "build.js");

const d = new Date();
const pad = (n) => String(n).padStart(2, "0");
const stamp =
  `${d.getFullYear()}.${pad(d.getMonth() + 1)}.${pad(d.getDate())} ` +
  `${pad(d.getHours())}:${pad(d.getMinutes())}`;

const banner =
  "/* AUTO-GENERATED by tools/build-stamp.mjs — do not edit by hand.\n" +
  " * Records the time of the last ./build.sh run for the footer stamp. */\n";

writeFileSync(outFile, banner + "\nconst BUILD_TIME = " + JSON.stringify(stamp) + ";\n");
console.log(`Wrote build time ${stamp} to assets/js/build.js`);
