/* ============================================================================
 * Compiles the friendly content files into assets/js/content.js (which the site
 * reads). Run:  node tools/build-content.mjs
 *
 * Edit text here — NOT in assets/js/content.js:
 *   content/about.en.yml  English text, grouped by section
 *   content/about.he.yml  Hebrew text, same keys as about.en.yml
 *   content/contact.yml   Phone / email / etc. (shared, not per-language)
 *
 * YAML you can use (a small, friendly subset — no quotes or commas needed):
 *
 *   nav:                       ← a group (indent its children by 2 spaces)
 *     about: About             ← a key and its text
 *     contact: Contact
 *
 *   about:
 *     p1: >                    ← ">" = a paragraph that can span several lines;
 *       This whole block is      line breaks become spaces, blank lines start
 *       joined into one          a new paragraph.
 *       paragraph.
 *     p2: |                    ← "|" = keep line breaks exactly as written.
 *       Line one.
 *       Line two.
 *
 * Lines starting with # are comments. That's all you need to know.
 * ========================================================================== */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseYaml, flatten } from "./yaml.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contentDir = join(root, "content");
const outFile = join(root, "assets", "js", "content.js");

function load(name) {
  return parseYaml(readFileSync(join(contentDir, name), "utf8"));
}

function main() {
  const contact = flatten(load("contact.yml"), "", {});
  const en = flatten(load("about.en.yml"), "", {});
  const he = flatten(load("about.he.yml"), "", {});

  // Warn about keys present in one language but missing in the other.
  const enKeys = Object.keys(en), heKeys = Object.keys(he);
  enKeys.filter((k) => !(k in he) && k !== "dir" && k !== "langName")
    .forEach((k) => console.warn(`! "${k}" is in about.en.yml but missing from about.he.yml`));
  heKeys.filter((k) => !(k in en) && k !== "dir" && k !== "langName")
    .forEach((k) => console.warn(`! "${k}" is in about.he.yml but missing from about.en.yml`));

  const banner =
    "/* AUTO-GENERATED by tools/build-content.mjs — do not edit by hand.\n" +
    " * Edit the text in content/about.en.yml, content/about.he.yml, content/contact.yml,\n" +
    " * then run:  node tools/build-content.mjs */\n";

  const body =
    "const CONTACT = " + JSON.stringify(contact, null, 2) + ";\n\n" +
    "const I18N = " + JSON.stringify({ en, he }, null, 2) + ";\n";

  writeFileSync(outFile, banner + "\n" + body);
  console.log(
    `Wrote ${enKeys.length} en / ${heKeys.length} he keys to assets/js/content.js`
  );
}

main();
